name: RegionFill
main: fromgate.regionfill.RegionFill
version: 0.1
website: http://www.minecraft-mccity.ru
author: fromgate, fromgate@gmail.com
authors: [Galaran]

depend: [WorldEdit, WorldGuard]

commands:
    rgfill:
        description: Fill region with defined block id and data
        permission: regionfill.command
        permission-message: You do not have permission
        usage: /<command> <world name> <region id> <block id>[:data]
    rgreplace:
        description: Replace blocks in region region
        permission: regionfill.command
        permission-message: You do not have permission
        usage: /<command> <world name> <region id> <from_id>[:data] <to_id>[:data]

permissions:
    regionfill.command:
        default: op