name: RegionFill
main: fromgate.regionfill.RegionFill
version: 0.0.1
website: http://www.minecraft-mccity.ru
author: fromgate, fromgate@gmail.com
depend: [WorldEdit,WorldGuard]
commands:
   rgfill:
      description: Fill region with defined block
      usage: |
           /rgfill <world name> <region name> <block id>
