name: RegionFill
main: fromgate.regionfill.RegionFill
version: 0.0.2
website: http://www.minecraft-mccity.ru
author: fromgate, fromgate@gmail.com
authors: [Galaran]

depend: [WorldEdit, WorldGuard]

commands:
    rgfill:
        description: Fill region with defined block id
        permission: regionfill.fillcommand
        permission-message: You do not have permission
        usage: /<command> <world name> <region name> <block id>

permissions:
    regionfill.fillcommand:
        default: op